export {default as Home} from './Home';
export {default as About} from './About';
export {default as Shop} from  './Shop'
export {default as Login} from './Login'
export {default as CustomerService} from './CustomerService'
export {default as Contact } from './Contact'
export {default as TrackOrder} from './TrackOrder'
export {default as ReturnOrder} from './ReturnOrder'
export {default as ShippingAndReturns} from './ShippingAndReturns'
export {default as ProductDetail} from './ProductDetail'
export {default as Account} from './Account'
export {default as Bag} from './Bag'
export {default as Checkout} from './Checkout'
export {default as PaymentStatus} from './PaymentStatus'
export {default as Wishlist} from './Wishlist'